name: Utc App ci/cd

on:
  push:
   branches: [ "main" ]
  pull_request:
    branches: [ "main"]

permissions:
  id-token: write
  contents: read
  
env:
  python_version: 3.11
  IMAGE_NAME: portfolio
  AWS_REGION: us-east-1
  ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
  ECR_REPO: ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/$IMAGE_NAME
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
            python-version: ${{ env.python_version }}  # or $python_version
      - name: Install pytest
        run: pip install -r requirements.txt
      - name: unit test
        run: pytest test.py

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_ARN }} 
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Login to Amazon ECR     # Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2


      - name: Build Docker image      # Build Docker image
        run: |
          docker build -t ${{ env.IMAGE_NAME }} .

      - name: Tag Docker image    # Tag image for ECR
        run: |
          docker tag ${{ env.IMAGE_NAME }}:latest ${{ env.ECR_REPO }}:latest


      - name: Run Trivy vulnerability scanner   # Scan image with TRIVY
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.ECR_REPO }}:latest
          format: table
          exit-code: '1'   # Fail workflows on critical/high vulnerabilities
          severity: CRITICAL,HIGH

     
      - name: Push image to ECR     # Push image to ECR
        run: |
          docker push ${{ env.ECR_REPO }}:latest
